#!/bin/bash

#############
# Autostart #
#############

#SXHKD
pgrep -x sxhkd > /dev/null || sxhkd &

#Dunst
dunst -b &

##############
# Appearance #
##############

#Wallpaper
feh --bg-fill ~/.wall.jpeg &

#Polybar
~/.config/polybar/launch.sh &

#Picom
picom --experimental-backends --backend glx -b &

#Cursor
xsetroot -cursor_name left_ptr

##############
#  BSPC      #
##############

#Workspaces
bspc monitor -d 1 2 3 4 5 6 7 8 9

#Borders and gaps
bspc config border_width         0
bspc config window_gap          15
bspc config split_ratio          0.5
bspc config gapless_monocle      false
bspc config paddingless_monocle	 true
bspc config automatic_scheme	spiral

#Mouse
bspc config focus_follows_pointer true
bspc config pointer_modifier	super
